services:
  frontend:
    build:
      context: ./dashboards
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    networks:
      - backend-net
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 300mb

  api-app:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8000:${API_PORT}"
    environment:
      MONGO_DATABASE_URI: ${API_DATA_URL}
      PORT: ${API_PORT}
    healthcheck:
      test: curl -f http://127.0.0.1:${API_PORT}/api/ || exit 1
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 20s
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 500mb
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    depends_on:
      - database
    networks:
      - backend-net

  database:
    image: mongo:6.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    healthcheck:
      test: mongo --username ${MONGO_INITDB_ROOT_USERNAME} --password ${MONGO_INITDB_ROOT_PASSWORD} --eval "db.adminCommand('ping')"
      interval: 10s
      timeout: 5s
      start_period: 30s
      retries: 5
    volumes:
      - "./.database:/data/db"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    networks:
      - backend-net

networks:
  backend-net:

volumes:
  prefect-data:
    driver: local
